import type { LessonContent } from "./lesson-data";

export type ExpansionTrack = {
  id: string; code: string; route: "Essential" | "Builder" | "Advanced"; hours: number;
  title: string; need: "Essential" | "Useful" | "Specialist" | "Optional" | "Curiosity";
  prerequisites: string[]; simple: string; outcome: string; whenNot: string;
  primary: string; freeAlternative: string; agnostic: string; proof: string;
  lessons: LessonContent[];
};

const lesson = (
  title: string, objective: string, explanation: string, example: string,
  activity: string, check: string, failureMode: string, passCriterion: string,
  transfer: string, resourceIds: string[],
): LessonContent => ({ title, objective, explanation, example, activity, check, failureMode, passCriterion, transfer, resourceIds });

export const expansionTracks: ExpansionTrack[] = [
  {
    id: "f0", code: "F0", route: "Essential", hours: 9, title: "Prediction, learning and uncertainty laboratory", need: "Essential", prerequisites: ["e1"],
    simple: "Turn introductory AI ideas into hand-worked predictions and honest uncertainty statements.",
    outcome: "Calculate small examples, detect leakage and distinguish a model score from a justified real-world conclusion.",
    whenNot: "Do not mistake this conceptual laboratory for professional machine-learning engineering or statistical advice.",
    primary: "Google ML Crash Course + transparent calculations", freeAlternative: "Paper, calculator and supplied synthetic tables",
    agnostic: "Target → features → split → baseline → error → uncertainty → fresh case.",
    proof: "A reproducible notebook or worksheet with correct arithmetic, a held-out check and bounded conclusions.",
    lessons: [
      lesson("Targets, features and baselines","Represent a prediction problem without leaking the answer into its inputs.","A target is the value to predict; features are information legitimately available at prediction time. A baseline establishes whether the learned method improves on a simple rule. Labels and features are design choices, not facts discovered automatically.","To predict whether a synthetic parcel is late, actual delivery time cannot be a feature because it is known only after the outcome. Always predicting the majority class supplies a measurable baseline.","For a twelve-row public-safe table, label target, candidate features, unavailable-at-decision fields and a simple baseline. Calculate the baseline result by hand.","Redesign a fresh scenario where a seemingly useful field becomes available only after the decision and justify its exclusion.","The learner includes a post-outcome field or reports model accuracy without comparing it with a baseline.","Every input has an availability rationale, baseline arithmetic reconciles with the rows and the target matches the real decision.","Transfer the design from a classification task to predicting a numeric quantity, choosing a suitable baseline.",["r08","r01"]),
      lesson("Training, validation and leakage","Separate fitting choices from an untouched check of how those choices generalise.","Training data supports parameter fitting; validation data supports development choices; a final test set estimates performance after those choices. Repeatedly inspecting the test set turns it into development data. Time, person and duplicate structure can leak across random splits.","Two rows from the same fictional customer placed on opposite sides of a split can make memorised identity look like generalisation. A time-ordered forecast cannot train on future records.","Split a small grouped, dated dataset three ways. Identify duplicates and explain why a purely random row split is misleading.","Given two competing preprocessing choices, select one with validation evidence and preserve the test rows until the decision is fixed.","The learner tunes repeatedly on the final test set or lets near-duplicate records appear in both training and evaluation.","The split respects the prediction timeline and grouping, documents every exclusion and keeps a genuinely unseen final check.","Adapt the split to a new school-year dataset where the same learner appears in multiple terms.",["r08","r73"]),
      lesson("Confusion matrices and error costs","Calculate class-specific outcomes and connect them to the consequence of each error.","Accuracy can conceal which cases fail. A confusion matrix separates true and false positives and negatives; precision and recall answer different questions. The appropriate trade-off depends on what happens after a prediction, not on which number sounds larger.","For 20 synthetic alerts with 6 real issues, if 5 issues are flagged and 3 harmless cases are also flagged, recall is 5/6 and precision is 5/8.","Fill a confusion matrix from individual predictions, calculate accuracy, precision and recall, then check every denominator against the table.","Choose a threshold for a low-stakes triage example using an explicit missed-case and false-alarm cost; do not generalise beyond the fixture.","A high overall accuracy hides failure on the smaller class or a metric is selected without reference to downstream consequences.","All cells and metrics reconcile, the chosen metric matches the declared consequence and limitations are stated without invented certainty.","Repeat for a balanced dataset where false alarms are more costly than missed cases.",["r08","r73"]),
      lesson("Calibration, uncertainty and model limits","State what a prediction score does and does not justify, then test confidence against observed frequencies.","A probability estimate is calibrated when similarly scored cases occur at roughly that rate in relevant data. Calibration does not prove individual correctness or transfer to a changed population. Small samples require especially cautious language.","Among ten synthetic cases assigned 0.8, only five succeed. That small batch does not match 80%, but it is too small to establish the long-run calibration error precisely.","Group supplied predictions into score bands, calculate observed frequencies and write a conclusion that distinguishes the observation from broader inference.","Diagnose a distribution shift where the evaluation population differs from training, naming which evidence must be recollected.","The learner calls 0.8 confidence an 80% guarantee for one person or ignores that deployment data changed.","Calculations preserve denominators, conclusions are sample-bounded and the proposed response to shift requires new evidence rather than confident extrapolation.","Apply the same uncertainty discipline to a language-model answer confidence statement with no numeric score.",["r08","r73","r18"]),
    ],
  },
  {
    id: "f1", code: "F1", route: "Essential", hours: 10, title: "Independent AI fluency and verification", need: "Essential", prerequisites: ["e0","e2"],
    simple: "Prove that you can use AI without surrendering arithmetic, source checking or your own explanation.",
    outcome: "Complete unfamiliar tasks with explicit checks, calibrated trust and a useful no-AI fallback.",
    whenNot: "Do not use this track to repeat beginner tutorials after the challenge tasks are already passed.",
    primary: "One available chatbot + ordinary verification tools", freeAlternative: "Browser, calculator, documents and paper",
    agnostic: "Attempt → compare → inspect → correct → explain → transfer → retest.",
    proof: "Four independent artifacts whose decisive claims or calculations were verified outside the generated answer.",
    lessons: [
      lesson("Tool-free first attempts","Expose your current reasoning before requesting assistance so feedback can target an actual gap.","An initial attempt creates evidence of what you know and where the first error occurs. It need not be long, but it must contain a real decision. Asking for an answer first makes recognition feel like understanding and obscures whether the tool improved performance.","Before asking for help with a short comparison, list the decision criteria and make a provisional choice. The AI can then challenge missing criteria instead of replacing the decision.","Complete two five-minute attempts: explain an AI concept and outline a small workflow. Record uncertainty before opening assistance.","Use AI feedback, then rewrite both answers closed-book and identify which correction changed your reasoning.","The original attempt is reconstructed after seeing the answer or consists only of vague keywords that cannot be marked.","The record preserves dated before/after work, identifies a specific corrected error and contains an unaided second explanation.","Apply the method to a non-AI academic or practical concept using a verified source.",["r85","r95"]),
      lesson("Calculation and table audits","Verify numerical outputs from original rows and explicit formulas rather than trusting plausible prose.","A correct-looking total can hide a missing row, wrong unit or inappropriate denominator. Recalculate decisive quantities with a calculator or spreadsheet, label units and reconcile totals. If the source table is incomplete, the correct result may be unknown.","Three quantities 12, 8 and blank do not justify a total of 20 if the blank means unreported rather than zero. The assumption changes the conclusion.","Audit a synthetic AI-produced table containing one transposed value, one unit error and one unjustified treatment of missing data.","Create a fresh summary from supplied rows and have another method independently reproduce the decisive total.","The learner asks a second chatbot to confirm the first or checks only the final arithmetic while ignoring omitted rows.","Every figure traces to a row and formula, units are consistent, missingness remains explicit and the decisive total is independently reproduced.","Audit a chart whose axis starts above zero and whose caption overstates the visible difference.",["r49","r50"]),
      lesson("Claim and citation audits","Open supporting material and test whether it establishes the adjacent claim.","A citation can be real, relevant to the topic and still fail to support the sentence. Check author or owner, date, passage, scope and contradictions. Preserve unsupported but useful ideas as hypotheses rather than facts.","A source describing a feature in an enterprise plan cannot establish that every free account has it. Product name similarity is insufficient.","Audit a synthetic five-claim memo with one fabricated source, one scope mismatch and one outdated statement.","Repair the memo using primary sources or an explicit unknown; include a claim-to-source table.","The learner counts citations or relies on search snippets without opening the material that supposedly supports the claim.","Each retained claim points to supporting evidence, the source scope matches the wording and unresolved contradictions remain visible.","Repeat with a numerical claim whose source reports a different population and measurement period.",["r15","r16"]),
      lesson("Independent fluency challenge","Route, execute and defend an unfamiliar low-stakes task using the smallest adequate toolset.","Fluency combines framing, tool choice, execution, verification and explanation. The challenge route may skip instruction but cannot skip evidence. A capable response also recognises when deterministic software or no AI is the better choice.","For a supplied event brief, a calendar table may need a spreadsheet and source checks; a model is optional for wording. Treating one chat answer as the whole workflow leaves the artifact and validation undone.","Choose one unseen task from document, research, data or planning categories. Write acceptance criteria and complete it independently.","Explain the route, show the decisive check, identify one limitation and repeat the task in a different format after a delay.","The result is polished but cannot be reproduced, or tool branding replaces evidence that the requested outcome exists.","The artifact meets its frozen criteria, external checks support material claims and the learner explains what AI did, what code did and what remained a human decision.","Solve the same class of problem when the preferred AI product is unavailable.",["r01","r11","r16"]),
    ],
  },
  {
    id: "p0", code: "P0", route: "Essential", hours: 18, title: "Documents, PDFs and accessible communication", need: "Essential", prerequisites: ["e2","e6"],
    simple: "Extract, reconcile and communicate evidence from documents without losing layout, provenance or accessibility.",
    outcome: "Produce an accurate report and presentation from mixed documents with traceable figures and accessible alternatives.",
    whenNot: "Do not upload restricted material or assume extracted reading order matches the visible page.",
    primary: "PDF/document tools + primary sources", freeAlternative: "Local readers, office software and a manual evidence ledger",
    agnostic: "Inspect → extract → reconcile → draft → verify → make accessible → reproduce.",
    proof: "A source-grounded report and presentation whose figures, quotations, structure and accessibility checks are reproducible.",
    lessons: [
      lesson("Document structure and extraction","Inspect visual and machine-readable structure before treating extracted text as the document.","Headings, tables, footnotes, columns and scanned pages may be lost or reordered during extraction. Record page locations and extraction limits. Use OCR output as a candidate transcription that needs comparison with the image.","A two-column PDF extracted across each row can join unrelated sentences. A table value without its column heading becomes meaningless.","Inspect a public PDF containing headings and a table. Compare visual order with extracted text and record three structural mismatches.","Create a clean excerpt with page references while leaving illegible or ambiguous values marked unknown.","The learner silently repairs OCR or reading order from context, creating plausible text not present in the source.","Every excerpt resolves to a page/region, table labels remain attached and uncertain transcription is visibly qualified.","Repeat with a scanned page and compare two extraction methods without assuming either is ground truth.",["r26","r16"]),
      lesson("Source reconciliation and long-document synthesis","Resolve overlapping, contradictory and superseded statements before producing a summary.","Long-context access does not choose which version governs. Build a claim ledger with document date, authority, scope and exact support. A synthesis should preserve conflicts until evidence justifies resolution.","A policy from 2024 and an amendment from 2025 disagree on a deadline. The later date alone may not settle scope unless the amendment says which cases it replaces.","Create a ten-claim ledger from three short synthetic documents including one amendment and one unresolved contradiction.","Write a bounded synthesis that distinguishes current rule, historical rule and unresolved interpretation.","The summary blends versions into one fluent rule or cites only the source supporting the preferred conclusion.","All material statements map to versioned passages, supersession is justified and unresolved conflicts remain explicit.","Reconcile a technical manual with release notes that modify only one operating mode.",["r16","r26","r89"]),
      lesson("Reports, tables and presentations","Choose a form that supports the audience's decision while keeping evidence inspectable.","A report explains reasoning; a table supports comparison; a presentation guides live attention. Reuse verified data rather than manually copying it into each format. Visual polish cannot rescue unsupported claims or inaccessible structure.","A three-option recommendation can link a comparison table to the narrative conclusion and reuse the same checked figures in slides.","Draft a two-page report from the reconciled ledger with one generated table and explicit limitations.","Create a five-slide briefing from the report and verify every number against the canonical table rather than retyping from memory.","Figures diverge across formats or the presentation removes the caveat that materially limits the recommendation.","Report and slides preserve the same verified facts, each format has a clear purpose and no critical qualification disappears.","Convert the briefing into a one-page handout for an audience that cannot attend the presentation.",["r16","r97"]),
      lesson("Accessibility, review and reproducible handover","Test whether another person can perceive, navigate and reproduce the document's essential meaning.","Accessible headings, table structure, meaningful link text, sufficient contrast and alternatives for visuals support real use. Automated checks help but do not establish usability. A handover also needs source files, version information and known limitations.","Alt text for a chart should convey its point and key data pattern, not merely say 'blue chart'. A slide title should identify the claim it presents.","Review the report and slides using heading navigation, keyboard-only reading order, text enlargement and a contrast or document checker.","Give a fresh reviewer the source ledger and handover instructions; record any reproduction or comprehension failure.","The learner reports accessibility passed solely because a checker found no errors or publishes only a flattened image/PDF.","Essential content has a usable alternative, navigation is coherent, source files remain editable and unperformed assistive-technology checks are disclosed.","Adapt the material for a narrow mobile display and a text-only export without losing the decision-critical evidence.",["r97","r16"]),
    ],
  },
  {
    id: "p1", code: "P1", route: "Essential", hours: 21, title: "Data and spreadsheet analysis", need: "Essential", prerequisites: ["f1"],
    simple: "Turn messy rows into checked analysis without hiding missing values or fragile formulas.",
    outcome: "Clean, analyse, visualise and hand over a reproducible spreadsheet with documented assumptions.",
    whenNot: "Do not use sensitive real records for practice or let AI-generated formulas bypass independent checks.",
    primary: "Excel or Google Sheets", freeAlternative: "LibreOffice Calc or CSV + Python",
    agnostic: "Profile → preserve raw → clean → validate → calculate → visualise → reconcile → hand over.",
    proof: "A reproducible workbook with preserved raw data, validated transformations, checked formulas and an evidence-bounded conclusion.",
    lessons: [
      lesson("Rows, fields, types and missing data","Profile a table before editing it and preserve the raw input as an immutable reference.","A row should represent one defined observation and each field one defined attribute. Dates, numbers and categories need explicit types. Blank, zero, not applicable and unavailable are different states and should not be collapsed casually.","A blank laboratory reading cannot automatically become zero; zero is a measured value with a different meaning.","Profile a synthetic CSV for duplicated keys, inconsistent dates, numeric text, category variants and missingness. Record counts before cleaning.","Design a clean table and data dictionary without modifying the preserved raw sheet.","The learner deletes inconvenient rows or replaces blanks with zero without a documented rule.","Raw counts reconcile, every transformation has a rule and missing categories remain distinguishable in the clean output.","Profile a second file where one logical observation is split across multiple rows.",["r50","r100"]),
      lesson("Formulas, lookups and validation","Build calculations whose references and failure behaviour can be inspected.","Relative and absolute references change when copied. Lookups require unique keys or an explicit duplicate policy. Validation should reject or flag invalid input rather than silently coercing it into a plausible value.","A lookup by learner name can return the wrong record when names repeat; a stable synthetic ID provides a safer key.","Implement totals, percentages and a lookup in a small workbook. Test normal, blank, duplicate-key and zero-denominator cases.","Audit a supplied formula containing a shifted range and a hidden error-handling function that turns failures into zero.","A formula appears correct on the first row but fails when filled down, or error suppression hides missing reference data.","Hand-calculated samples match formulas, copied references remain correct and invalid cases are visible with an explained policy.","Replace the lookup table with one whose column order changes and preserve correct results.",["r50","r109"]),
      lesson("Aggregation, charts and uncertainty","Summarise groups with appropriate denominators and design charts that preserve the scale and limits of the data.","Means can be distorted by outliers and missingness; percentages need explicit denominators. A chart should show what was measured and avoid visual choices that exaggerate small differences. Uncertainty includes both sampling variation and data-quality limits.","If 20 of 25 submitted responses agree, report 20/25 among submitted responses—not 80% of all 40 invited people.","Create grouped counts, median and mean from a supplied table. Build one chart and annotate the denominator, missing cases and measurement period.","Write a three-sentence interpretation that distinguishes observation, plausible explanation and evidence not collected.","A truncated axis or selected subset makes a modest difference look dramatic, or a percentage omits its denominator.","Aggregates reconcile with filtered rows, the chart can be interpreted without hidden filters and conclusions remain within the observed data.","Choose a different chart for a time series containing a gap and explain why interpolation would mislead.",["r08","r50"]),
      lesson("Reproducibility, audit and data project","Deliver a workbook that another person can update, test and explain after the original conversation is gone.","Separate raw, cleaned, analysis and output layers. Record source, update time, transformation rules and checks. A beautiful dashboard is not reproducible if manual edits cannot be traced or formulas depend on private local paths.","A control total can compare cleaned row counts and summed amounts against the raw import, revealing an accidental dropped row.","Build a complete public-safe workbook from raw fixture to decision summary. Add control totals, a change log and three refresh instructions.","Have a clean environment or reviewer replace the raw fixture with a compatible new file and follow the handover.","The workbook only works on the author's device, pasted values sever provenance or an unexplained filter changes the headline result.","Refresh succeeds from documented inputs, control totals catch a planted defect and every material conclusion traces to the analysis layer.","Migrate the analysis to CSV + Python while preserving the same acceptance checks and explain which approach is easier to audit.",["r50","r100","r51"]),
    ],
  },
  {
    id: "p2", code: "P2", route: "Essential", hours: 18, title: "Professional workflows and decision support", need: "Useful", prerequisites: ["e2","f1"],
    simple: "Use AI for communication, planning and delegation while keeping decisions, authority and evidence human-owned.",
    outcome: "Design and hand over a bounded professional workflow with checked outputs and explicit approval points.",
    whenNot: "Do not connect live accounts or send consequential messages merely to complete a training exercise.",
    primary: "ChatGPT Work or another reviewable workspace", freeAlternative: "Chat + checklist + ordinary office files",
    agnostic: "Frame → gather → draft → check → approve → execute → observe → hand over.",
    proof: "A complete synthetic workflow package with source evidence, approval boundaries, verified output and recovery notes.",
    lessons: [
      lesson("Writing, editing and communication workflows","Separate the message objective and facts from stylistic revision.","AI can generate and restructure language, but the sender remains responsible for accuracy, tone and recipients. Preserve facts and unresolved questions in a source note; use editing criteria rather than repeated requests to make prose better.","A concise status email should not transform 'delivery date unconfirmed' into a promised Friday deadline for fluency.","Create a fact sheet and draft a short update for two audiences. Audit every concrete claim and record which tone changes are preferences.","Revise an inaccurate generated draft while preserving its useful structure and explaining the correction.","A polished message introduces a commitment, recipient or emotional claim that the source material did not authorise.","The final text matches the fact sheet, distinguishes unknowns and has a clear purpose appropriate to its audience.","Convert the same facts into meeting notes where decisions, actions and unresolved issues have separate sections.",["r11","r20"]),
      lesson("Meetings, tasks and connected-app delegation","Translate discussion into candidate actions without confusing a generated plan with executed external changes.","Connected tools can read or write only within granted permissions. Drafting an event, task or message is different from saving or sending it. Bind approval to the exact action, account, destination and content, then verify the external state when execution is authorised.","A meeting transcript says 'consider contacting the supplier'; that is not a decision, assigned owner or permission for the assistant to send email.","Extract decisions, proposed actions, owners and unknowns from a synthetic transcript. Prepare drafts using mock accounts only.","Design an approval card for one external action and specify what observation would prove it completed exactly once.","The workflow upgrades a suggestion into a commitment or reports a requested tool call as a saved calendar event.","Every action traces to an authorised decision, drafts remain distinguishable from sends and completion requires destination evidence.","Adapt the workflow to a task app that can create duplicates after a timeout.",["r20","r90"]),
      lesson("Decision analysis and human judgment","Use structured comparison to expose assumptions, trade-offs and uncertainty rather than outsourcing the decision.","Define objectives and constraints before scoring options. Weights express judgment; AI cannot make them objective. Sensitivity analysis shows whether a recommendation changes under plausible weights or missing information.","Option A scores 4 on cost and 2 on reliability; B scores 2 and 4. Equal weights tie them, while a reliability-heavy decision favours B. The calculation cannot decide which value matters more.","Build a small decision table for three fictional options with source-linked facts and explicitly chosen weights.","Change two plausible assumptions and explain whether the recommendation is stable, unstable or blocked by missing evidence.","Generated scores are treated as measurements or a weighted total conceals a mandatory constraint that one option violates.","All factual scores trace to evidence, subjective judgments are labelled and the recommendation reflects constraints and sensitivity rather than one arbitrary total.","Repeat using a non-AI option that removes a privacy or operating-cost risk.",["r18","r50"]),
      lesson("Operational handover and workflow repair","Leave the next operator with state, evidence and recovery instructions rather than a polished summary alone.","A handover should distinguish completed, pending, failed and unverified work; identify exact artifacts and versions; and explain the next safe action. Repair the smallest failed stage without repeating external effects that may already have occurred.","After a document is saved but its confirmation times out, the next step is to inspect the destination—not blindly regenerate and save another copy.","Run a synthetic multi-stage workflow with one ambiguous completion. Produce a state ledger and resolve it using a read-only check.","Hand the package to a fresh reader and record whether they can resume without repeating or inventing work.","The handover calls planned actions completed or omits the decision that would materially change the result.","Artifacts, observations and pending authority are explicit; the next action is bounded and recovery avoids duplicate effects.","Resume after a long break when one product interface has changed, preserving stable task principles and verified outputs.",["r20","r21","r90"]),
    ],
  },
  {
    id: "d0", code: "D0", route: "Builder", hours: 20, title: "Databases and typed application foundations", need: "Essential", prerequisites: ["b0","b3"],
    simple: "Store structured information with explicit keys, constraints and tested application boundaries.",
    outcome: "Design a small relational database and connect it to a typed application with safe migrations and failure tests.",
    whenNot: "Do not use real credentials or production data; a spreadsheet remains better for small, single-user tables without application logic.",
    primary: "SQLite + SQL + TypeScript or Python", freeAlternative: "Browser SQL sandbox and supplied local fixtures",
    agnostic: "Model → constrain → query → transact → migrate → integrate → test → recover.",
    proof: "A reproducible application and database whose constraints, migrations, queries and rollback behaviour pass independent tests.",
    lessons: [
      lesson("Tables, keys and relational models","Translate a real information requirement into entities, stable identifiers and explicit relationships.","A table models one kind of record. Primary keys identify rows; foreign keys connect records. Normalisation can reduce conflicting copies, but excessive fragmentation can make simple work harder. Model the questions and constraints the application actually needs.","Using a learner's name as a key fails when names repeat or change. A generated learner ID can remain stable while names are attributes.","Model a synthetic reading list with learners, sources and reviews. Draw keys, required fields and one-to-many relationships before writing SQL.","Test the model against duplicate names, a missing source and deleting a referenced row.","The design stores comma-separated IDs, duplicates changing facts across tables or has no policy for orphaned references.","Every required query is supported, identifiers remain stable and relationship constraints produce the intended accept/reject behaviour.","Adapt the schema to allow multiple authors per source without duplicating the source record.",["r59","r50"]),
      lesson("SQL queries and data integrity","Retrieve and modify data while preserving explicit filters, joins and constraints.","SELECT chooses columns and rows; joins connect related records; aggregates change the unit being counted. Parameter binding keeps data separate from query syntax. Database constraints should enforce critical rules even when application validation fails.","Counting joined review rows answers a different question from counting distinct sources. A bound parameter is safer than concatenating untrusted text into SQL.","Create the schema in SQLite, insert public-safe fixtures and write queries for three named questions. Add uniqueness, null and foreign-key constraints.","Repair a query that double-counts after a join and a write that should be rejected by a database constraint.","A query returns plausible totals while multiplying rows, or validation exists only in the user interface.","Expected rows and aggregates are hand-checked, parameters are bound and invalid writes fail at the database boundary.","Write the same report using a subquery or grouped join and compare the query plans conceptually.",["r59","r50"]),
      lesson("Transactions, migrations and recovery","Make multi-step changes atomic and evolve a schema without silently losing valid data.","A transaction groups related writes so they commit together or roll back together. A migration records a deliberate schema transition. Back up and test migration on a copy; rollback may require a separate down path or restore procedure.","Creating an order and reducing stock must not leave only one change committed after a failure. Adding a non-null column requires a plan for existing rows.","Implement a transaction over two synthetic tables and force the second write to fail. Verify the first write did not persist.","Write and test a migration that adds a constrained field to existing fixture data, including a restore or reversal demonstration.","The migration edits production-like data without a verified copy or assumes transactional DDL behaves identically in every database.","Before/after counts reconcile, forced failure leaves the old state intact and exact source/migration versions are recorded.","Migrate a field from free text to a referenced lookup table while preserving unknown historic values.",["r51","r59"]),
      lesson("Typed integration and database project","Connect application input to storage through validated types and observable errors.","Static types describe developer assumptions; runtime validation checks actual data. Keep database access behind a narrow interface, map expected failures to useful messages and test using an isolated database. Do not expose connection secrets to browser code.","A TypeScript number annotation cannot stop an HTTP request containing the string 'twelve'. Runtime parsing must reject or transform it deliberately.","Build a small API or command-line application over the schema. Validate create/read/update inputs and return distinct not-found, conflict and invalid-input errors.","Run integration tests against a fresh database, then reproduce setup from the README and a pinned migration sequence.","Tests share state, errors leak internal details or the client bundle contains a database credential.","A clean setup passes normal and failure cases, concurrent or repeated requests respect constraints and recovery steps preserve data.","Replace the interface layer—for example CLI with HTTP—while retaining the same database contract and tests.",["r51","r59","r109"]),
    ],
  },
  {
    id: "r0", code: "R0", route: "Advanced", hours: 18, title: "Working RAG systems and measured retrieval", need: "Specialist", prerequisites: ["a1","d0"],
    simple: "Build and evaluate a retrieval-grounded system whose evidence path can be inspected.",
    outcome: "Implement ingestion, hybrid retrieval, grounded generation and failure-driven repair against a labelled corpus.",
    whenNot: "Do not add RAG when direct context or deterministic lookup meets the requirement more reliably.",
    primary: "A small public corpus + local or hosted retrieval stack", freeAlternative: "Keyword index, SQLite and manually supplied context",
    agnostic: "Inventory → ingest → chunk → index → retrieve → rerank → construct → answer → evaluate.",
    proof: "A working RAG project with a no-RAG baseline, labelled retrieval set, citation audit and measured repair.",
    lessons: [
      lesson("Corpus governance and ingestion","Control what enters the knowledge base and retain provenance through transformation.","Ingestion should identify source, version, access scope, extraction method and checksum or equivalent identity. Reject unsupported or corrupted material visibly. Updating and deleting sources must not leave stale chunks searchable.","A revised policy file with the same title must not coexist as an apparently current duplicate unless versioned intentionally.","Build a manifest for ten public-safe documents, ingest them and trace three chunks back to exact source locations.","Replace and delete selected documents, then prove obsolete passages no longer appear in retrieval.","The index cannot identify which source version produced a chunk or silently skips failed extraction.","Manifest, chunk records and index reconcile; failures are reported and update/delete tests remove only intended content.","Ingest a scanned or table-heavy source and record what the extraction process cannot preserve reliably.",["r104","r115"]),
      lesson("Hybrid retrieval, metadata and reranking","Combine lexical and semantic evidence only when the labelled queries show a need.","Keyword retrieval protects exact identifiers; vector retrieval helps paraphrases; metadata restricts scope; reranking reorders candidates. Each layer can fail independently and adds cost. Evaluate the simplest baseline before adding complexity.","An exact regulation code may rank poorly semantically but match lexically. A metadata filter can keep an archived edition out of current-policy results.","Implement keyword and vector or simulated-semantic retrieval on the same corpus. Fuse results with a documented rule and apply one metadata constraint.","Use labelled queries to compare recall at a fixed cutoff before and after reranking; inspect losses as well as gains.","The stack grows more complex while measured recall stays unchanged or a filter excludes the only relevant source.","Per-query rankings, relevant labels and latency are retained, and added components earn their place on the frozen evaluation set.","Transfer the design to multilingual or code-like identifiers where tokenisation changes retrieval behaviour.",["r77","r119","r104"]),
      lesson("Context construction, grounding and citations","Assemble retrieved evidence so the answer can use it without confusing source text with instructions.","Context construction selects, orders and labels chunks under a budget. Require claim-level support and permit abstention. Deduplicate repeated evidence, preserve source boundaries and treat embedded instructions as untrusted data.","Three overlapping chunks repeating one statement do not provide three independent sources. A cited document may still fail to support the exact generated sentence.","Build an answer stage over retrieved chunks with source labels, an unknown response and a citation format resolving to source locations.","Audit ten answers for evidence use, unsupported synthesis, citation correctness and context overflow.","The answer cites a relevant document but invents a relation between two facts, or follows an instruction embedded in a chunk.","Every material claim has supporting passages, unanswerable cases abstain and source content cannot expand tool authority.","Answer a multi-hop question requiring two sources and identify when the available evidence does not justify combining them.",["r76","r78","r104"]),
      lesson("RAG evaluation, repair and deployment","Diagnose retrieval, context and generation separately, then prove a targeted repair on unchanged cases.","End-to-end answer scores alone cannot identify which stage failed. Keep retrieval labels, answer references, adversarial cases and a no-RAG baseline. Re-run regressions after corpus or model changes and monitor stale-source behaviour.","If the correct chunk ranks 12th, prompt editing cannot repair a top-five retrieval miss. If it ranks first but the answer ignores it, retrieval is not the failing stage.","Run at least 20 labelled queries across answerable, unanswerable, exact-match and poisoned-source slices. Classify every failure by stage.","Repair the highest-impact cause, rerun the frozen set and prepare a reproducible local or preview deployment with rollback.","The test set is edited to make the repair look successful or an improved mean hides a critical adversarial regression.","The report shows before/after slice metrics, retained failures, cost/latency assumptions and a working checked artifact tied to exact source.","Update the corpus with a conflicting later document and test the version-selection and monitoring policy.",["r73","r78","r104","r119"]),
    ],
  },
  {
    id: "g0", code: "G0", route: "Advanced", hours: 20, title: "Constrained agents, MCP and reliable automation", need: "Specialist", prerequisites: ["b5","b6","a3","a5"],
    simple: "Build one useful agentic workflow whose state, permissions and recovery are explicit.",
    outcome: "Integrate tools or MCP with durable state, approvals, idempotency, observability and adversarial failure tests.",
    whenNot: "Do not use an agent where a deterministic workflow is simpler or connect training code to real consequential accounts.",
    primary: "Mocked tools + an MCP-capable client", freeAlternative: "Local function calls and a deterministic state machine",
    agnostic: "Goal → state → route → tool → observe → validate → approve → commit → recover → stop.",
    proof: "A constrained system that outperforms its deterministic baseline on a justified task without exceeding authority or duplicating effects.",
    lessons: [
      lesson("Agent state and deterministic baselines","Prove which decisions require model judgment before creating an agent loop.","Start with a deterministic workflow and explicit state. Agents are useful when inputs vary and a model must choose among bounded actions; they are costly when a fixed sequence suffices. Represent pending, completed, failed and uncertain work separately.","A weekly file rename uses a deterministic script. Researching which of several sources answers a changing question may justify bounded model selection.","Implement a deterministic baseline for a synthetic intake task and record its failures on ten cases.","Add one bounded model decision only where the baseline cannot express the requirement; compare finished-task quality and complexity.","The design calls any multistep script an agent or stores a generated plan as proof that steps completed.","State transitions are inspectable, the added decision has measured value and the loop has maximum actions and a stop state.","Remove the model decision after changing the requirement to a fully structured input and verify the simpler path.",["r69","r70","r75"]),
      lesson("MCP tools, resources and trust boundaries","Expose the narrowest capabilities needed and enforce their schemas and permissions at the server boundary.","MCP standardises discovery and invocation but does not make a server safe. Tools perform actions; resources provide context. Authenticate callers, validate arguments, restrict data and treat returned content as untrusted when it re-enters model context.","A read-only resource server should reject a model-requested write even when the request is syntactically valid. A tool description is not an access-control rule.","Configure or build a local synthetic MCP server exposing one resource and one harmless tool. Record discovery and a valid call.","Test malformed arguments, a denied item, an excessive result and an instruction embedded in tool output.","The server trusts client-side validation, logs secrets or exposes all files because the client requests only one folder in practice.","Allowed calls succeed, denied calls fail outside the model, outputs are bounded and the trace contains no real credentials.","Replace MCP with ordinary function calls and explain which protocol benefits and risks remain or disappear.",["r66","r67","r68","r90"]),
      lesson("Idempotency, approvals and recovery","Prevent uncertain or repeated execution from creating duplicate consequential effects.","A write needs a stable logical operation identity and reconciliation after ambiguous failure. Approval must bind to exact arguments and expire or be reconsidered after material change. Retry transient reads differently from writes, validation errors and permission denials.","If a mock task creation times out after the server stores it, retrying with a new identifier creates a duplicate; checking the original operation ID can recover safely.","Implement a local side-effect ledger and a mock write that sometimes loses its acknowledgement. Reconcile and retry without duplicates.","Add an approval step, change one consequential argument after approval and prove re-approval is required.","Every exception is retried or a blanket approval authorises different recipients and content.","Normal, timeout, denial and changed-action tests terminate predictably; exactly one intended effect exists and uncertainty stays visible until reconciled.","Transfer to a scheduled workflow that may wake twice for the same due item.",["r69","r72","r90"]),
      lesson("Observability, security evaluation and agent project","Evaluate the complete workflow under realistic failures and preserve a recovery path.","Logs should connect decisions, tool calls and state changes without retaining unnecessary private content. Security tests cover injection, over-privilege and malicious outputs; reliability tests cover timeouts, partial work and stop requests. Compare against the baseline with unchanged cases.","A successful final answer can conceal three duplicated tool calls and a denied action. Outcome, process and authority all need evidence.","Run at least 20 synthetic cases including ordinary, ambiguous, timeout, injection-marker, denied-action and stop-request slices.","Repair one measured failure, rerun all cases and prepare a public-safe demonstration, architecture note and rollback procedure.","The agent is evaluated only on its final prose or adversarial testing omits benign controls and real authorisation limits.","The system meets a declared quality floor, has zero unapproved effects, bounded cost/actions and a reproducible restore; remaining failures are disclosed.","Swap one tool implementation or MCP server and repeat the security and idempotency checks without changing acceptance rules.",["r73","r78","r81","r87"]),
    ],
  },
  {
    id: "pr0", code: "PR0", route: "Advanced", hours: 28, title: "Integrated portfolio projects", need: "Essential", prerequisites: ["p0","p1","b7","a3"],
    simple: "Turn separate skills into four bounded, inspectable artifacts before attempting graduation.",
    outcome: "Complete research, data, software and systems projects with independent acceptance, transfer and evidence review.",
    whenNot: "Do not begin four oversized greenfield builds; adapt earlier work and finish vertical slices that another person can inspect.",
    primary: "Your existing Atlas artifacts and public-safe repositories", freeAlternative: "Local files, screenshots and recorded demonstrations",
    agnostic: "Scope → reuse → build → verify → review → transfer → document → retain.",
    proof: "Four passed portfolio projects with reproducible artifacts, self-reported evidence, known limits and at least one reviewed transfer.",
    lessons: [
      lesson("Research and evidence project","Complete a defensible investigation whose claims, exclusions and uncertainty another reader can audit.","Reuse the research protocol and document skills rather than starting with a blank topic. Choose a question small enough for source-level checking. Distinguish a rigorous mini-review from an exhaustive or expert-reviewed synthesis.","A ten-source contradiction map with explicit search bounds is more defensible than a fifty-link report with no screening record.","Select a public-safe question, freeze protocol and acceptance criteria, then build a source ledger, evidence matrix and concise report.","Ask a fresh reviewer to locate support for five sampled claims and reproduce one search; retain failures and corrections.","The report implies consensus from incomplete coverage or obscures exclusions and AI-assisted drafting.","Claims trace to opened evidence, contradictions remain visible and the reproduction package works without private accounts.","Update the project after a new contradictory source and record how the conclusion changes or remains bounded.",["r16","r89","r73"]),
      lesson("Data and decision project","Turn a raw public-safe dataset into a checked decision artifact with transparent assumptions.","A portfolio data project should preserve raw input, transformation rules, formulas or code, and a decision-relevant output. Its conclusion must reflect data limits rather than the sophistication of its chart or dashboard.","A reproducible workbook plus a short interpretation can outperform a larger dashboard whose filters and calculations are hidden.","Choose a modest dataset, define three questions and build the complete raw-to-output pipeline with control totals.","Have another method or reviewer reproduce one decisive measure and test an edge case that changes a conclusion.","Manual edits sever the analysis from raw data or a visual encodes an unsupported causal story.","Refresh and checks are reproducible, all figures reconcile and the conclusion distinguishes observation from inference.","Recreate the decisive output in a different tool while preserving acceptance criteria and source identity.",["r50","r73"]),
      lesson("Software and deployment project","Ship a small application that solves one real task and survives independent setup and failure testing.","Reuse the coding, Git, API and database work. A portfolio artifact needs an exact source revision, tests, clear setup, privacy-safe fixture and a demonstrated primary workflow. Public hosting is optional when local operation is safer or sufficient.","A local document validator with five strong acceptance cases is a better artifact than an unfinished platform with twenty promised features.","Write non-goals, implement one vertical slice and add regression, invalid-input and recovery tests before deployment or recording.","Reproduce the setup in a clean environment and verify the destination workflow or local demonstration from the README.","The project depends on undisclosed local state, generated tests mirror a wrong implementation or deployment is claimed from a build log alone.","Exact source, artifact and observed workflow agree; failure states are useful and rollback or clean removal is demonstrated.","Change one interface or storage dependency without rewriting the whole project, then rerun frozen tests.",["r51","r52","r84"]),
      lesson("AI systems, evaluation and security project","Integrate RAG, agents, MCP or automation only where the selected problem earns their complexity.","Choose one systems project, reuse earlier components and compare with a simpler baseline. Include evaluation slices, threat model, authority controls, observability and repair evidence. Do not require every learner to build every possible architecture.","A constrained RAG assistant and a scheduled deterministic report are different valid choices; the problem and evaluation determine which belongs.","Select one pathway, document architecture and trust boundaries, then run ordinary, failure and adversarial cases against a frozen suite.","Present the artifact, failed example, repair, residual risk and maintenance plan in a concise portfolio narrative.","The system is judged by framework count, hides unapproved tool effects or claims reliability from a single successful run.","It beats or justifies itself against the baseline, critical gates pass and another reviewer can inspect evidence without sensitive data.","Transfer the system to a new corpus, tool or schedule and demonstrate which assumptions require revalidation.",["r73","r78","r87","r110"]),
    ],
  },
  {
    id: "c0", code: "C0", route: "Advanced", hours: 20, title: "Core capstone, specialisation and graduation defence", need: "Essential", prerequisites: ["pr0","a6"],
    simple: "Demonstrate independent system judgment through one chosen capstone and a delayed defence.",
    outcome: "Frame, build, evaluate, defend and transfer one portfolio-grade system while meeting core graduation evidence.",
    whenNot: "Do not count elapsed hours, planned work or legacy click states as graduation evidence.",
    primary: "One chosen specialisation using the existing portfolio", freeAlternative: "Local-only artifact with reproducible recording and review pack",
    agnostic: "Frame → defend scope → build → evaluate → red-team → repair → transfer → delayed defence.",
    proof: "One passed core capstone, chosen specialisation, inspectable portfolio, fresh transfer and delayed independent retest across required competencies.",
    lessons: [
      lesson("Capstone proposal and architecture defence","Choose one consequential but bounded problem and justify every AI component against a simpler alternative.","The proposal must name user, decision, evidence, constraints, non-goals, risks and success criteria. Select one specialisation rather than accumulating giant capstones. Prior artifacts may be reused when their assumptions are rechecked.","A research-and-learning system may reuse the RAG project while adding learner attempts and evidence controls; copying it unchanged does not demonstrate synthesis.","Write a proposal, architecture and prerequisite evidence index. Include a no-AI or deterministic baseline and explicit data/authority boundaries.","Defend the proposal against questions about scope, failure cost, privacy, verification and why AI is appropriate.","The project starts implementation before the decisive requirement is defined or includes components whose contribution cannot be tested.","The proposal fits available time, maps every requirement to a check and identifies the human who retains final authority.","Reframe the same problem under a constraint that prohibits the originally selected model or cloud service.",["r18","r51","r73"]),
      lesson("Independent build and evaluation","Complete the primary workflow under frozen acceptance criteria and retain evidence from failed attempts.","The independent build phase integrates earlier competencies without continuous worked-output scaffolding. Instrument the system, test realistic cases and separate model behaviour from application, data and human decisions. Assistance must be disclosed.","A correct final answer reached after an unbounded hidden retry loop is not the same system as a bounded one whose first accepted output passes.","Build the smallest complete version, record exact source/configuration and execute normal, edge and critical-failure cases.","Compare against the baseline and produce a failure taxonomy with quality, latency, cost or resource assumptions and human corrections.","The learner changes test expectations after failures or discards unsuccessful runs from the portfolio.","The artifact meets frozen critical gates, retained evidence supports reported metrics and untested claims remain explicitly unverified.","Have an independent reviewer or clean environment reproduce the primary workflow and one failure case.",["r51","r73","r75"]),
      lesson("Security, reliability and portfolio review","Show that the system fails safely, recovers and communicates its limits to a real reviewer.","Threat modelling identifies assets, trust boundaries and misuse paths; reliability testing covers timeouts, malformed input, unavailable tools and restoration. A portfolio review checks truth of claims, accessibility, privacy and reproducibility, not promotional polish.","A model refusal does not protect a database if the executor accepts over-broad arguments. A passing unit test does not prove the live or local release workflow works.","Run the capstone threat model and controlled failure drills using synthetic data. Demonstrate least privilege, stop behaviour and recovery.","Audit the entire portfolio for private material, unsupported performance claims, inaccessible artifacts and missing setup evidence.","A policy statement substitutes for an enforced control or a public portfolio includes a real private artifact without consent.","Critical failures are blocked outside model discretion, recovery restores verified state and every public claim points to evidence or a limitation.","Ask a reviewer with different access needs to use the portfolio and document unperformed assistive-technology or domain review.",["r78","r81","r83","r97"]),
      lesson("Transfer, delayed defence and independent mastery","Demonstrate that the capability survives a new context and a meaningful delay.","Graduation requires core units and projects at the defined evidence stages, one selected capstone path, a materially different transfer and a delayed independent retest. A scheduled retest, old legacy claim or total hour count cannot substitute for performance.","Adapting a policy RAG system to equipment manuals changes document structure, failure stakes and evaluation cases. Changing only branding does not test transfer.","Complete a fresh transfer with hidden prior outputs, record what changed and pass the same critical principles in the new setting.","After at least seven days, defend the architecture closed-book, diagnose a planted failure and implement a bounded change; record assistance honestly.","The learner rehearses the identical demonstration or backfills dates and evidence after seeing the graduation result.","Required competencies reach independent standard, transfer is materially distinct, delayed work exists and any failed dimension routes to a specific repair.","Create a model-change survival update that replaces a volatile product detail while preserving the stable workflow and evaluation design.",["r73","r85","r95","r121"]),
    ],
  },
];
